name: deployStaging
on:
  push:
    branches: [ "staging" ]
  pull_request:
    branches: [ "staging" ]
  workflow_dispatch:
jobs:
  makeOutput:
    runs-on: ubuntu-latest
    outputs:
      ENVIRONMENT: ${{ steps.derp.outputs.ENVIRONMENT }}
    steps:
      - uses: actions/checkout@v3
      - name: derpid
        id: derp
        run: |
          echo "ENVIRONMENT=staging" >> $GITHUB_OUTPUT
   
  buildStaging:
    needs: makeOutput
    environment:
      name: ${{ needs.makeOutput.outputs.ENVIRONMENT }}
      url: "https://${{ needs.makeOutput.outputs.ENVIRONMENT }}.derpalerp.com"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: |
          echo ${{ needs.makeOutput.outputs.ENVIRONMENT }};
      
 
